name: hydroadjust-dev
channels:
  - conda-forge
dependencies:
  - gdal
  - numpy
  - scipy
  - tqdm
  - geopandas
  - shapely
  - jupyter
  - jupyterlab
  - ipykernel
  # For testing only
  - pytest
  # For development
  - pip
  - pip:
    - -e .
